name: Generate Docs Update

on:
  push:
    branches: 
          - test-docs
jobs:
  build_docs_job:
    name: Code Reference Generator
    runs-on:
      labels: [self-hosted, linux, x64]

    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
              token: ${{ secrets.GITHUB_TOKEN }}
              
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
              python-version: 3.9.0

      - name: Install dependencies
        run: |
              python -m pip install -U sphinx
              python -m pip install furo
              python -m pip install django
              python -m pip install mock
              pip install sphinxjp.themes.basicstrap
              cd docker 
              cd requirements
              pip install python_ldap-3.3.1-cp39-cp39-win_amd64.whl
              pip install sphinxjp
              pip install -r base.txt

      - name: Make the Codebase Reference sphinx docs
        run: |
              cd docs/codebase_docs/ 
              sphinx-apidoc -o source ../../CodeListLibrary_project
              sphinx-build -b html source ..

      - name: Copy Documentation
        run: |
          ls -l 
          rm -r docker
          rm -r CodeListLibrary_project  
          cd docs 
          rm -r _modules
          rm -r _sources
          rm -r _static 
          rm -r assets
          rm -r codebase_docs
          rm -r sql-scripts
          rm -r unit-testing

      - name: Init new codebase docs repo
        run: |
              touch .nojekyll
              git add -A
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git commit -m "Update documentation and Allure reports"



      - name: Deploy report to gh-pages branch
        if: (success() || failure()) && github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: github-pages
          PUBLISH_DIR: docs
          keep_files: true
