name: Run Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          export $(grep -v '^#' docker/selenium-testing/env/remotetest.compose.env | xargs)
          cd CodeListLibrary
          pytest -v -s --cov-report xml --cov . --html=report.html --self-contained-html -k ""
        env:
          DISPLAY: ":99"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: CodeListLibrary_project/report.html
          retention-days: 5
